/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei/native";

export default function Model(props) {
  const { nodes, materials } = useGLTF(require('../assets/model.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pasted__model1.geometry}
        material={materials.koltuk}
      />
      <mesh
        geometry={nodes.pasted__model2.geometry}
        material={materials.siyah}
      />
      <mesh
        geometry={nodes.pasted__model3.geometry}
        material={materials.metal}
      />
      <mesh
        geometry={nodes.pasted__model4.geometry}
        material={materials.siyah}
      />
      <mesh
        geometry={nodes.pasted__model5.geometry}
        material={materials.siyah}
      />
      <mesh
        geometry={nodes.pasted__model6.geometry}
        material={materials.altin}
      />
      <mesh
        geometry={nodes.pasted__model7.geometry}
        material={materials.koltuk}
      />
    </group>
  );
}

useGLTF.preload(require('../assets/model.glb'));
